Add `X-
equinor/webviz pull request #28
Opened 2023-02-09 13:57 UTC by anders-kiaer

2023-03-16 12:41 UTC, rubenthoms requested changes
Please keep in mind that code in `frontend/src/api` should not be edited manually (see comment).

2023-03-17 07:25 UTC, anders-kiaer commented on frontend/src/api/ApiService.ts
> -            BASE: config?.BASE ?? '/api',
Yes, it is the latter. I will modify 👍

2023-03-17 07:42 UTC, rubenthoms requested changes

2023-03-17 07:42 UTC, rubenthoms commented on frontend/src/framework/ApiService.ts
> +            BASE: "/api",
You could remove this line here (BASE), since it’s already set to ‘/api’ by default.

2023-03-17 12:07 UTC, rubenthoms approved these changes

2023-03-17 12:09 UTC, merged