Realization filter
equinor/webviz pull request #571
Opened 2024-02-01 12:43 UTC by jorgenherje

2024-02-08 15:28 UTC, rubenthoms requested changes
Great job! A couple of rename suggestions and some minor issues.

2024-02-09 10:17 UTC, jorgenherje commented on frontend/src/framework/internal/components/NavBar/rightNavBar.tsx
> +        setFilterPanelExpanded(newExpanded);
That's true!

2024-02-09 10:46 UTC, jorgenherje commented on frontend/src/framework/GuiMessageBroker.ts
> +    [GuiState.FilterPanelExpanded]: boolean;
👍

2024-02-09 11:01 UTC, jorgenherje commented on frontend/src/framework/RealizationFilter.ts
> +    private _parentEnsemble: Ensemble;
Changed to `_assignedEnsemble` as ensemble is assigned to the filter on creation.

2024-02-09 11:04 UTC, jorgenherje commented on frontend/src/framework/components/RealizationPicker/realizationPicker.tsx
> +                    "text-slate-800 hover:text-slate-600 text-sm cursor-pointer flex items-center out",
Have no clue where it comes from, probably a typo.

2024-02-09 11:44 UTC, rubenthoms commented on frontend/src/framework/RealizationFilter.ts
> +    private _parentEnsemble: Ensemble;
Perfect!

2024-02-14 14:04 UTC, rubenthoms approved these changes
One small change, otherwise, good to go :+1:

2024-02-14 14:04 UTC, rubenthoms commented on frontend/src/framework/internal/components/RealizationFilterSettings/realizationFilterSettings.tsx
> +            setCandidateEnsembleIdent(ensembleIdent);
This is also a duplicate and could be moved to line 78.

2024-02-14 14:17 UTC, merged