Implementation of `VFPINJ` curves in the `VFP` module.
equinor/webviz pull request #738
Opened 2024-09-24 12:44 UTC by lindjoha

Implementation of `VFPINJ` curves in the `VFP` module.

2024-09-25 16:19 UTC, jorgenherje requested changes
Some comments, otherwise it looks good to me!

Suggest to create an utility function to check if a table is a prod table, as mentioned in comments below. This utility can be updated in the future, s.t. all checks within the module looks to the same "criteria" for categorizing a table as a prod table.

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("wfr_values" in this._vfpTable) { // This means that it is a VFPPROD table
Consider using suggested `isProdTable`-utlity for if-check

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("wfr_values" in this._vfpTable) { // This means that it is a VFPPROD table
Consider using suggested `isProdTable`-utlity for if-check

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("wfr_values" in this._vfpTable) { // This means that it is a VFPPROD table
Consider using suggested `isProdTable`-utlity for if-check

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("wfr_values" in this._vfpTable) { // This means that it is a VFPPROD table
Consider using suggested `isProdTable`-utlity for if-check.

I'd reverse the if-check to, s.t. error is thrown in if-statement and larger amount of code is outside if:

```
if (!isProdTable(this._vfpTable)){
  throw Error("The getVfpProdBhpValues function is not valid for VFPINJ tables.")
}

const nbWfrValues = this._vfpTable.wfr_values.length
const nbGfrValues = this._vfpTable.gfr_values.length
const nbAlqValues = this._vfpTable.alq_values.length
const nbFlowRates = this._vfpTable.flow_rate_values.length
const startIndex = nbFlowRates*(nbAlqValues*(nbGfrValues(nbWfrValues*thpIndex+wfrIndex)+gfrIndex)+alqIndex)
return this._vfpTable.bhp_values.slice(startIndex, startIndex+nbFlowRates)

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("gfr_type" in this._vfpTable) { // This means that it is a VFPPROD table
Consider using suggested `isProdTable`-utlity for if-check.

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("alq_type" in this._vfpTable) { // This means that it is a VFPPROD table
Consider using suggested `isProdTable`-utlity for if-check.

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("wfr_type" in this._vfpTable) { // This means that it is a VFPPROD table
Consider using suggested `isProdTable`-utlity for if-check.

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        throw Error("The getVfpInjBhpValues function is not valid for VFPPROD tables.")
Consider using suggested `isProdTable`-utlity for if-check.

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("wfr_values" in this._vfpTable) { // This means that it is a VFPPROD table
Consider using suggested `isProdTable`-utlity for if-check.

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpPlotBuilder.ts
> +        if (selectedThpIndices == null) {
Use strict equality ===

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/view.tsx
> +        if (vfpTable.vfp_type == VfpType_api.VFPPROD) {
Use strict equality ===

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/view.tsx
> +        } else if (vfpTable.vfp_type == VfpType_api.VFPINJ) {
Use strict equality ===

2024-09-25 16:19 UTC, jorgenherje commented on backend_py/primary/primary/services/sumo_access/vfp_access.py
> +        if vfp_type == VfpType.VFPPROD:
Use strict equality ===

2024-09-25 16:19 UTC, jorgenherje commented on frontend/src/modules/Vfp/settings/atoms/derivedAtoms.ts
> +    if (vfpTable?.vfp_type == VfpType_api.VFPINJ && ["WFR", "GFR", "ALQ"].includes(userSelectedColorBy)) {
Use strict equality ===

2024-09-26 10:24 UTC, lindjoha commented on backend_py/primary/primary/services/sumo_access/vfp_access.py
> +        if vfp_type == VfpType.VFPPROD:
This is python :D

2024-09-26 11:00 UTC, jorgenherje commented on backend_py/primary/primary/services/sumo_access/vfp_access.py
> +        if vfp_type == VfpType.VFPPROD:
Haha. Sorry, my bad! 👍

2024-10-18 08:24 UTC, jorgenherje requested changes
Looks good to me! Just some minor comments, then it's good to go!

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("isProdTable" in this._vfpTable) { // This means that it is a VFPPROD table
Use `isProdTable()`-function instead?

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("isProdTable" in this._vfpTable) { // This means that it is a VFPPROD table
Use `isProdTable()`-function instead?

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("isProdTable" in this._vfpTable) { // This means that it is a VFPPROD table
Use `isProdTable()`-function instead?

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
>          if (vfpParam == VfpParam.THP) {
Use strict equality `===`

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("isProdTable" in this._vfpTable) { // This means that it is a VFPPROD table
Use `isProdTable()`-function instead?

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if ("isProdTable" in this._vfpTable) { // This means that it is a VFPPROD table
Use `isProdTable()`-function instead?

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if (!("isProdTable" in this._vfpTable)) {
Use `isProdTable()`-function instead?

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +        if(!("isInjTable" in this._vfpTable)) {
Use `isProdTable()`-function instead?

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +export function isProdTable(vfpTable: VfpProdTable_api | VfpInjTable_api): vfpTable is VfpProdTable_api {
Consider placing the function in a separate file in the `utils`-folder. Name it e.g. `vfpTableClassifier.ts`

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
Minor issue: Did not see this last time, but file names should be starting with lower case letters, i.e. `vfpDataAccessor.ts`

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
>          } else if (flowRateType == FlowRateType_api.GAS) {
Use strict equality `===`

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
> +            if (vfpParam == VfpParam.ALQ) {
Use strict equality `===`

2024-10-18 08:24 UTC, jorgenherje commented on frontend/src/modules/Vfp/utils/VfpDataAccessor.ts
>          if (vfpParam == VfpParam.THP) {
Use strict equality `===`

2024-10-20 08:01 UTC, merged