Adjustments to backend in preparation of 2D viewer
equinor/webviz pull request #808
Opened 2024-11-18 14:59 UTC by rubenthoms

2024-11-26 07:55 UTC, Anders2303 requested changes
Overall, looks good to me, nice work! I found some smaller issues that should be resolved before I think we're good to merge

2024-11-26 07:55 UTC, Anders2303 commented on frontend/src/modules/Intersection/view/view.tsx
> +                fieldName = fieldIdentifier;
Could optionally be further shortened to `const fieldName = fieldIdentifier ?? ""`

2024-12-03 08:03 UTC, HansKallekleiv commented on backend_py/primary/primary/services/smda_access/smda_access.py
I agree some separation should be added as this will grow, but for now I want to keep it in one file.
When we are more confident on how we organize different datatypes across services we can revisit this.

2024-12-03 08:04 UTC, HansKallekleiv commented on backend_py/primary/primary/services/smda_access/smda_access.py
> +            )
I guess this can be discussed. Feedback from an earlier PR was the opposite :) 
I will keep it like this for now.

2024-12-03 08:08 UTC, HansKallekleiv commented on backend_py/primary/primary/services/smda_access/drogon/drogon_smda_access.py
> +        return get_drogon_strat_units()
Unused-argument used as this class returns mocked data and arguments are not in use.
want to keep the same signature as the real class.

2024-12-03 08:10 UTC, HansKallekleiv commented on backend_py/primary/primary/services/smda_access/smda_access.py
> +                    break
they might be of different lengths as there can be wellbores without any survey data.
Added a lookup dict to avoid the nested loop

2024-12-03 14:02 UTC, Anders2303 approved these changes
LGTM!

2024-12-03 14:03 UTC, merged