Refactor `SimulationTimeSeriesSensitivity` to use jotai
equinor/webviz pull request #833
Opened 2024-12-18 15:13 UTC by jorgenherje

- Refactor front-end
- Minor adjustments back-end for statistics end-point (should use real filter)

2025-01-15 12:06 UTC, Anders2303 requested changes
Looks good to me. Found some small nitpicks; notably that you can simplify the query configs now, as #768 is merged

2025-01-16 08:24 UTC, jorgenherje commented on frontend/src/modules/SimulationTimeSeriesSensitivity/settings/utils/fixupVectorName.ts
> +    if (!availableVectorNames || availableVectorNames.length === 0) {
Good point, I just performed copy+paste of function and missed this detail.

2025-01-16 08:26 UTC, jorgenherje commented on frontend/src/modules/SimulationTimeSeriesSensitivity/view/atoms/queryAtoms.ts
> +        gcTime: CACHE_TIME,
I've now merged main into this branch, and updated the queries to new generated api-functions. These are now removed

2025-01-16 12:05 UTC, Anders2303 approved these changes

2025-01-16 12:06 UTC, merged